### ISSUE TITLE
generate-values.sh script command shown is incorrect

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/docs-tas-kubernetes#21]
On this page: https://docs.pivotal.io/tas-kubernetes/0-2/configuring-installation-values.html

the command shown to use the `generate-values.sh` script is:

`./bin/generate-values.sh -d "PLACEHOLDER-SYSTEM-DOMAIN" > ../configuration-values/deployment-values.yml`

The correct command is:

`./bin/generate-values.sh -d "PLACEHOLDER-SYSTEM-DOMAIN" > ./configuration-values/deployment-values.yml`

This is because the user is already in the `tanzu-application-service` folder, and only 1 period is needed before referring to a sub-folder.

I wasn't allowed to just make a PR, so I decided to create this issue.

**Comment by ograves-pivotal** [comment]
Closing as the task has been completed. Twice!
