### ISSUE TITLE
Private Registry Installation is not accurate

### ISSUE THREAD

**Issue by mhoshi-vm** [pivotal-cf/docs-tas-kubernetes#45]
Performing private registry installation does not work as expected.

**1. The value `registry.SYSTEM-DOMAIN/ORG-NAME/REPOSITORY` does not work.**

The following guides us to login to registry.SYSTEM-DOMAIN/ORG-NAME/REPOSITORY but there is no registry running on this url
https://docs.pivotal.io/tas-kubernetes/0-3/optional-image-relocation.html#uploading-the-images
We assumed that this points to the local private so we specified our local repo which is "registry.vmware.local"
The `kbld package` was okay with this but was this correct ?

**2. The correct value to pass to the "-r" flag at "kbld unpackage"** 
For `kbld unpackage` does not work with `-r registry.vmware.local`. 
I tested at my local env but i realized that if I specify something `-r registry.vmware.local/repo/cf` the commands succeeds.
However I see every 38 images gets named as "registry.vmware.local/repo/cf" (identified with different digest) in Harbor and I was unsure was this correct.

**3. The correct to flag to update the images with "kbld -f- -f relocated.yml"**
In my lab I tested with the same command that is specified here
https://docs.pivotal.io/tas-kubernetes/0-3/installing-tas-for-kubernetes.html#post-image-relocation
However, the image url becomes 
<private_registry>/tas-for-k8s/<original image name>
But as written in 2, all the images are the same name (with different digest) so this did not work. So either my procedure at 2. or 3. is  wrong.

**Comment by paigecalvert** [comment]
Thank you! I checked in with the TAS for K8s team, and it sounds like you've subsequently submitted a PR with some updates to this procedure. Closing out this issue.
